# Setup
title:               rupert.k
tagline:             '#개발 #데이터분석 #머신러닝'
description:         '일에서 재미를 찾아 다닙니다'
url:                 https://blog.rupert.in
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              rupert yoonsub kim
  url:               https://www.linkedin.com/in/rupert-kim/
  email:             my@rupert.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
# Disqus
discus-identifier: blog-rupert-in # add your discus identifier